In [1]:
import numpy as np

In [4]:
print np.zeros(10)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [6]:
print np.eye(3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [13]:
print np.ones(5)

[ 1.  1.  1.  1.  1.]


In [15]:
print np.arange(2, 20, 3)

[ 2  5  8 11 14 17]


In [16]:
# create array from python list

In [17]:
list1 = [1,2,3]

In [18]:
print np.array(list1)

[1 2 3]


In [19]:
print np.array(list1) + 1

[2 3 4]
